### ISSUE TITLE
Docked title is very short

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/discourse-nav#22]
*Note - filling in this form will file an issue against the discourse.charmhub.io website navigation*

## Summary

On a small screen scroll down on a topic and see the title is truncated very early.

## Process

- Go to a topic
- scroll down and see the header comes with it and the title is truncated with available space.

## Current and expected result

The title should take up the space before being truncated.

## Screenshot

![Screenshot_20210501-090006.jpg](https://user-images.githubusercontent.com/1413534/116775646-0c006e00-aa5c-11eb-8b2c-62cdc17e2a88.jpg)

https://discourse.charmhub.io/

**Comment by solazio** [comment]
Fixed it.
![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/78f0d876-7b15-4306-ad32-579acc2e0774)
