### ISSUE TITLE
Headings seem more subtle

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/discourse-nav#23]
*Note - filling in this form will file an issue against the discourse.charmhub.io website navigation*

## Summary

The heading styles used in the discourse theme do not have enough strength.

## Process

- Go to https://discourse.charmhub.io/t/juju-2-9-0-release-notes/4525
- Scroll down to the heading "Granular control of application expose setting by operators"
- See the headings are light and the same or less font-size

## Current and expected result

Headings should be clear and stand out as a section divider

## Screenshot

![Screenshot_20210501-090400.jpg](https://user-images.githubusercontent.com/1413534/116775832-1a9b5500-aa5d-11eb-9fa8-5d149002d75a.jpg)

**Comment by solazio** [comment]
This is fixed now. Closing

![image](https://user-images.githubusercontent.com/40214246/117113548-8560cf00-ad82-11eb-8fe6-5efa472a42f6.png)

**Comment by anthonydillon** [comment]
I still see the same issue? What changed?

**Comment by solazio** [comment]
I thought this is more obvious. Is using the vanilla typography. Can you please suggest what to do with it. Should I just make the headings bolder?

**Comment by anthonydillon** [comment]
The following styling local on discourse is overriding the Vanilla font-size:
```css
.cooked h3, .d-editor-preview h3 {
    font-size: 1.1487em;
}
```
The [Vanilla font-size](https://vanillaframework.io/docs/base/typography#heading-classes) should be `1.70596rem`.

**Comment by anthonydillon** [comment]
This is what it looks like if you remove the local override:
![image](https://user-images.githubusercontent.com/1413534/117145356-fae09580-adaa-11eb-8fab-3b9690f5314e.png)

**Comment by Lukewh** [comment]
Is this issue still relevant? Seems very outdated. Closing reopen if needed.
