### ISSUE TITLE
sticky nav is broken

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/discourse-nav#27]
go [here](https://discourse.charmhub.io/tag/news)

![Screenshot 2021-06-17 at 12.06.34.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/89823622-1c96-41b3-a4ba-afcefae751cd)

**Comment by clagom** [comment]
Thanks Ana, we got a similar issue here #1052 that includes another page too, so closing this one.
