### ISSUE TITLE
Images not showing in forum posts

### ISSUE THREAD

**Issue by igorljubuncic** [canonical-web-and-design/discourse-nav#6]
*Note - filling in this form will file an issue against the forum.snapcraft.io website navigation*

## Summary
Inline image in a forum post is not showing, e.g.:
https://forum.snapcraft.io/t/snapcraft-clinic/20166

## Process
Try to view any page that should display an image but does not.

## Current and expected result
I made a change to the thread - after the update, the expected inline image does not show.

## Browser details
Happens in multiple browsers.

## URL
https://forum.snapcraft.io/
https://forum.snapcraft.io/t/snapcraft-clinic/20166

**Comment by anthonydillon** [comment]
@igorljubuncic It looks like the image upload failed. Do you have the original image which we can try and upload again?

**Comment by ghost** [comment]
I don't have the original anymore, unfortunately. The image upload did not fail, the image was showing up for several months until the blank space inset began showing up.

**Comment by ghost** [comment]
Has there been any update on this please?

**Comment by jkfran** [comment]
Hi @igorljubuncic ,

I just test it, and it is working fine. By the looks of it, the upload of that particular image failed at some point, which could be because a network issue.

I updated the post with the latest image that you had on that topic, if it was a different image we can't recover it.
