### ISSUE TITLE
The section links (like “Latest” and “New”) in the hamburger menu aren’t working

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/discourse-nav#7]
*Note - filling in this form will file an issue against the forum.snapcraft.io website navigation*

## Summary

Since this update, on mobile, the section links (like “Latest” and “New”) in the hamburger menu aren’t working for me when I’m on a post. They do work fine on one of the section homepages.

## Process

[List the steps to replicate the issue.]

## Current and expected result

[Describe what happened and what you expected.]

## Screenshot

[If relevant, please include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

## URL

[Add below the url of the page where the issue occurs]

https://forum.snapcraft.io/

**Comment by solazio** [comment]
I cannot reproduce this in any browser or layout. Closing, please reopen if needed.

**Comment by elcste** [comment]
I finally had time to look at this more systematically. I noticed it on my mobile browser (Bromite on Android), but can reproduce in a desktop browser with a narrow window. I tried Chromium 90 and Firefox 88 on Ubuntu.

What I found is the entries in the hamburger menu work fine when triggered at the top of page, either a category page or post page. You can see the hover effect on the link and the link URL in the status bars in the bottom left.

![cr-post-menu](https://user-images.githubusercontent.com/915687/116017412-1dcdb580-a605-11eb-956e-7cbe2164f42d.png)
![fx-menu](https://user-images.githubusercontent.com/915687/116017443-3342df80-a605-11eb-9772-ebdb5c5c61c7.png)

But once you scroll down the page, so the nav bar loses the dark Canonical bar, then the menu entries don't work, both in posts and in category pages. (You'll need one that's long enough to scroll, like "Latest".) Any clicks just go to the content below the menu, here's no hover effect on the link, and the status bar only shows link if the content below (i.e in the post or category listing).

![cr-latest-menu-docked](https://user-images.githubusercontent.com/915687/116017427-26be8700-a605-11eb-8b48-205afe11a5fc.png)
![cr-post-menu-docked](https://user-images.githubusercontent.com/915687/116017432-29b97780-a605-11eb-8ca3-f66e939c9d4c.png)
![fx-menu-docked](https://user-images.githubusercontent.com/915687/116017452-38a02a00-a605-11eb-9348-770f2b4b3210.png)

**Comment by steverydz** [comment]
@elcste this should be fixed now. Please re-open if you're still having problems.
