### ISSUE TITLE
Discourse should be Snapcraft Forum

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/discourse-nav#8]
I would like to ask whether the “Discourse” label is customizable? I expect it to be “Snapcraft Forum” or something more appropriate, rather than the forum software’s title.

![image](https://user-images.githubusercontent.com/40214246/115024205-ad61be80-9eb7-11eb-9a2d-64153c4cbc44.png)

**Comment by tbille** [comment]
I think it is perfectly fine to keep `Discourse` since the forum is using discourse. Discourse is popular enough that we can keep this name I believe.

If we had to rename just `Forum` is enough.

**Comment by Lin-Buo-Ren** [comment]
> Discourse is popular enough that we can keep this name I believe.

Discourse is indeed popular, however, I failed to see why most people will know the solution name while using it as most of the Discourse-based forums don't actually show the name.

`Forum` is fine for me though...

**Comment by tbille** [comment]
I had my thought over the weekend and changed my mind. I think you are right we should replace `Discourse` with `Forum`. In this scenario it makes more sense.

**Comment by Lin-Buo-Ren** [comment]
`Snapcraft Forum` is supposed to be the brand(?) name of the forum, though...

**Comment by tbille** [comment]
@Lin-Buo-Ren It feels there would be a lot of "Snapcraft" on the header if we go with Snapcraft forum
![image](https://user-images.githubusercontent.com/2707508/115205893-ee451780-a0f1-11eb-826d-ca5f9e8a5b2f.png)

vs.

![image](https://user-images.githubusercontent.com/2707508/115205944-fa30d980-a0f1-11eb-802b-15e21051b730.png)

I think it is quite explicit that you are on Snapcraft forum.

**Comment by Lin-Buo-Ren** [comment]
> I think it is quite explicit that you are on Snapcraft forum.

Understood.

**Comment by tbille** [comment]
Header updated.
